<a href="https://colab.research.google.com/github/omkarpattnaik8080/Pandas/blob/main/Numpy001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
l=[1,2,3,4]

In [3]:
ar=np.array(l)

In [4]:
ar

array([1, 2, 3, 4])

In [5]:
type(ar)

numpy.ndarray

In [6]:
np.array([[1,2],[3,4]]) #for a 2dimensional array

array([[1, 2],
       [3, 4]])

In [7]:
a=[2,3,4]

In [8]:
np.asarray(a) #also can be used to convert normal list into array and #ASANYARRAY WORKS THE SAME

array([2, 3, 4])

In [9]:
#MATRIX
#yeah bydefault 2d hota hai
b=np.matrix(l)

In [10]:
b

matrix([[1, 2, 3, 4]])

In [11]:
#THERE WILL BE NO CONVERSION IF I USE ASANYARRAY WITH b BCZ ITS ALREADY A ARRAY MATRIX IS A SUBSET OF ARRAY
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [12]:
a=np.array(l)

In [13]:
a

array([1, 2, 3, 4])

In [14]:
a=np.array(l)

In [15]:
c=a

In [16]:
c

array([1, 2, 3, 4])

In [17]:
#accesing elements of c
c[0]

1

In [18]:
c[0]=100

In [19]:
c

array([100,   2,   3,   4])

In [20]:
#to copy the elements of a we can use copy
d=np.copy(a)

In [21]:
d

array([100,   2,   3,   4])

In [22]:
a[1]=400

In [23]:
#but there will be no change in d as it undergoesdeepcopy
d

array([100,   2,   3,   4])

In [26]:
#functions in numpy
np.fromfunction(lambda i,j : i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])